### ISSUE TITLE
external interrupt for zero crossing?

### ISSUE THREAD

**Issue by jandrassy** [AJMansfield/TriacDimmer#10]
What is the advantage of using timer capture over external interrupt? I made this and then I discovered your library and I try to understand.

```
const byte TRIAC_PIN = 9;
const byte ZC_EI_PIN = 2;

unsigned long topMicroseconds = 9700; // 10000 micros is between zero crossings
int prescaler = 8;
byte prescalerBits = _BV(CS11); // /8

void zeroCrossing() {
  TCNT1 = 0; // reset the timer counter
}

void setup() {
  Serial.begin(115200);
  Serial.println("START");

  attachInterrupt(digitalPinToInterrupt(ZC_EI_PIN), zeroCrossing, RISING);

  pinMode(TRIAC_PIN, OUTPUT);
  uint32_t topPeriod = ((F_CPU / 1000000)* topMicroseconds) / prescaler ;
  ICR1 = topPeriod;
  OCR1A = topPeriod + 1;
  TCCR1A = _BV(WGM11) | _BV(COM1A0) | _BV(COM1A1);
  TCCR1B = _BV(WGM13) | _BV(WGM12) | prescalerBits;
}

void loop() {
  if (Serial.available()) {
    unsigned long microseconds = Serial.parseInt();
    Serial.find("\n");
    uint32_t period = ((F_CPU / 1000000)* microseconds) / prescaler ;
    OCR1A = period;
  }
}

```
I use [Robotdyn Dimmer](https://robotdyn.com/ac-light-dimmer-module-1-channel-3-3v-5v-logic-ac-50-60hz-220v-110v.html)

**Comment by AJMansfield** [comment]
The main point of using input capture is to ensure correct timing even if the interrupt code ends up running later than expected.
There are a number of reasons that an interrupt might run late, the most obvious being if it's preempted by a _different_ interrupt, or if the code does anything involving `cli();` and `sei();` blocks.

A less obvious source of error are multi-cycle opcodes. When the interrupt occurs, the interrupt doesn't start until the current instruction finishes.

On top of that there's the setup time for the interrupt itself, where the interrupt has to save the current register state so the CPU can resume the interrupted code when the interrupt ends. While the set-up time doesn't change while the code is running, small code changes and different compiler versions can change it.

And for soft interrupts defined with `attachInterrupt();` there's additional time needed for the pin interrupt dispatcher to determine the correct callback function and call it.

In any case, there's always at least a small delay from the input edge to when your code actuallly starts running, and while there are some things you can do to compensate for the delay by adding some kind of offset to the timer, the delay isn't always constant either.

However, the input capture hardware suffers no such limitation; in fact the entire reason it exists is to eliminate this sort of error.
Even if the interrupt runs several timer ticks late, the input capture hardware will have recorded the exact zero-crossing time, and the code can use it to set up the output compare registers at an offset from the actual event rather than from the possibly-late interrupt code.

There's also another small side benefit of allowing the timer count to freewheel and keep overflowing rather than resetting it: this preserves the prescaler subcycle value. Any time you set TCNT it clears the prescaler to 0, but by keeping it intact it's kinda like the hardware will automatically add "leap seconds" making the output average to a more precise value on average. This is a much smaller effect than anything else here but it exists.

**Comment by jandrassy** [comment]
what largest time differences between captured time and interrupt execution did you observed? is it significant compared to long 10 milliseconds of the AC half wave? even if the triac is switched at steepest part of the wave, does this shift make a distance in delivered power/brightness?

In my code pin is set HIGH at compare match and LOW at timer overflow. Timer top is set to happen before zero crossing.  Then the timer continues from zero. I return it to zero in the ZC interrupt. With OCR1A value for less then 400 micros the triac will stay ON and with values over 9600 microseconds the triac stays off.

**Comment by AJMansfield** [comment]
It really depends on what other code you have running alongside the library. I've seen it be as much as 100 microseconds out just with rapid serial communication (using the UART interrupt for receiving MIDI data, etc) and with some libraries that are particularly poorly-written it can be even worse.

If all you're doing is waiting in an idle loop though it's not a problem. Basically, the busier your microcontroller is, the worse it gets.

**Comment by jandrassy** [comment]
thank you

**Comment by AJMansfield** [comment]
Yeah, if the cpu is just idling the non-input-capture code will probably work fine, phase-cut dimming isn't _so_ sensitive that a few microseconds out will ruin anything.

But at the same time, it's easy enough to just use the input capture, so why put up with that error at all? At worst it's only slightly better, but it's one less thing to worry about if and when your project expands and starts demanding more CPU resources.
The only _real_ downside of using input capture is the need to use a specific input pin on the arduino for the zero crossing detection.

**Comment by jandrassy** [comment]
my code works with only one interrupt. I think I prefer that.

**Comment by AJMansfield** [comment]
My code works with only one `#include <TriacDimmer.h>"`. 😜

Real talk though, those interrupts exist regardless of whether or not you're using them, and they can't very well be used for anything else since you're already using the timer peripheral for this.
You might as well use the interrupts _designed_ to handle events related to the timer instead of wasting a general-purpose interrupt on it.

Also, note that all `attachInterrupt` does is put a function pointer to your callback in an array, and then in the PCINT interrupt it checks all the pins to see which one changed before calling the function pointer. (There's a lot of other nastiness behind the inner workings of soft interrupts but I won't bore you with the details.)

There's also two other issues with the code you have: Your code only works on 50Hz power, and it drives the triac gate far longer than the 20 microsecond spec.

Part of the extra complexity in the library code comes from the fact that my library actually _measures_ the mains frequency and uses the _measured_ period to adjust the length of the phase cut, and the ease and accuracy of doing this is one of the big advantages of using the input compare.
This allows the code to work on both 50Hz and 60Hz mains (or even 400Hz aircraft mains) without modification, and also compensates for any small inaccuracies from the nominal mains frequency or CPU clock.

As for driving the gate extra long: The entire point of the two output compare interrupts in the library is to cut the pulses short, and if that wasn't needed you could remove them entirely. (Some stuff would need to be changed elsewhere to support it, but in principle at least.)

While code that overdrives the gate will mostly still work, it generates more heat and can cause flickering for phase cuts close to the full waveform period, as the overdriven triac will occasionally trigger right at the start of the waveform. Now, your code does solve the flickering issue by just turning off the load entirely for phase cuts longer than 9700 &mu;s, always giving the gate at least 300 &mu;s to discharge. That is a reasonable solution: for a purely resistive load the jump from 9700 &mu;s to entirely off _is_ only a 0.4% difference in RMS voltage and a 0.002% difference in delivered power. But it does result in more heat, and if you need to go lower than 1.1 volts RMS a short pulse allows you to trigger the triac much closer to the zero crossing without issue.

**Comment by jandrassy** [comment]
I made many variations of triac control code. Starting from [no direct registers use](https://arduino.stackexchange.com/questions/63631/fan-regulator-control-from-arduino/63674#63674) to completely with registers. And not only for AVR. I have versions for SAMD too. All other versions do only a short pulse, only this one doesn't. To do a short pulse on AVR a second interrupt is necessary. SAMD has one-shot wave output so TOP can be set short after compare match. And SAMD can trigger timer on external interrupt without interrupt function.
