### ISSUE TITLE
Use with potentiometer?

### ISSUE THREAD

**Issue by nsummy** [AJMansfield/TriacDimmer#20]
Hi, I am attempting to use this with a potentiometer and am not able to get it to work at all.  I realize its looking for a floating point value between 0 and 1.  Is there a good way to set this up?  Or a simple way to modify the source to use an integer input?  Unfortunately I am still learning to code, so while I understand the problem, I am not sure of the solution.  Thanks :)

**Comment by AJMansfield** [comment]
In theory it would be possible to implement an API that accepts and rescales an integer input on some arbitrary scale, but either way the library would still need to rescale that input in order to track with variations in the mains frequency (or, more realistically, drift in the arduino's clock frequency), so it didn't really seem worth it to me.

BTW pro tip, instead of the whole `floatMap` lerp thing, you can just write `analogValue / 1023.0f`. (The `f` makes it a `float` literal rather than a `double` literal.) Way shorter and easier to read IMO.

If you _do_ need better performance or control though, you can absolutely use the control variables defined in [TriacDimmer::detail](https://github.com/AJMansfield/TriacDimmer/blob/master/src/TriacDimmer.h#L108-L161) directly. They're an intentional part of the library's API to make it possible to exert more low-level control over the behavior of the interrupts, and any changes to those values are immediately reflected in the output. If you do use that API though, make sure to use an `ATOMIC_BLOCK` (or at least `cli();` and `sei();`) around accesses that should happen together to ensure 100% glitch-free operation; take a look at how [TriacDimmer::detail::setChannelA](https://github.com/AJMansfield/TriacDimmer/blob/master/src/TriacDimmer.cpp#L91-L103) is implemented if you want to see what I mean. (If you don't use an atomic block, you could end up with the ISR reading a partially-written value and messing up the timing for a half-cycle. Not the end of the world, but it's just also completely avoidable too.)
