### ISSUE TITLE
Please, add STOP/RUN command on demand

### ISSUE THREAD

**Issue by woodlist** [AJMansfield/TriacDimmer#7]

**Comment by AJMansfield** [comment]
Can you elaborate on what you mean? How would this be different from the existing `begin` and `end` functions?

**Comment by woodlist** [comment]
Dear, I agree that my wish was realised originally and is ready to use. Please, advise, what will happen, if synchronization will take run at 50Hz, which means that I would like to run just one half of sine wave?

**Comment by woodlist** [comment]
"volatile uint16_t TriacDimmer::detail::period = 16667;"
Is this the period of main grid in microseconds?

**Comment by AJMansfield** [comment]
The line you're referring to, `volatile uint16_t TriacDimmer::detail::period = 16667;`, is actually updated constantly by the code to reflect the actual _measured_ mains period (or, technically, the _half_ period measured in _half_-microseconds). The 16667 is just an initial value I use to avoid numerical issues.

To be absolutely pedantic it could be changed to 20000 for 50Hz, but the way the code is written that's not necessary.
As long as you're calling the `TriacDimmer::setBrightness` function at regular intervals in your main loop, the phase offset will be recomputed from the measured mains period, which then also corrects for any inaccuracy in the arduino's clock crystal or with the mains frequency. 

As for pulse length: The default pulse length, 10 microseconds, is the recommended value for the [board I designed this library to work with](https://www.amazon.com/Dimmer-Module-Controller-Arduino-Raspberry/dp/B06Y1GVG26), but if you're designing your own circuit you will need to work out the appropriate pulse length yourself. There's a million and one things that affect it; you will probably need to determine it experimentally, just by trying values to see if they work.

**Comment by woodlist** [comment]
The last thing that remains unresolved for me is the sync pulse active part being. Please, indicate, is the falling to"0" active or not?

**Comment by AJMansfield** [comment]
Oh, that's what you mean.
As written, the library is designed to trigger on the rising edge, and should work with any pulse longer than around 1 &mu;s.

The code that defines this is found at [TriacDimmer.cpp:16-18](https://github.com/AJMansfield/TriacDimmer/blob/master/src/TriacDimmer.cpp#L16-18):

```
	TCCR1B = _BV(ICNC1)  //input capture noise cancel
			| _BV(ICES1) //positive edge
			| _BV(CS11); // /8 prescaler
```

If you want to change this to use a negative edge, you can comment out line 17 (`| _BV(ICES1)`).

For a more detailed explanation of what exactly is happening here I'd recommend reading [chapter 13 of the ATmega328p datasheet](https://www.sparkfun.com/datasheets/Components/SMD/ATMega328.pdf#page=113), which gives a detailed explanation of how the AVR counter/timer peripheral works.

Note that the /8 prescaler (`_BV(CS11)`) is required due to the time periods involved, and on a .
The /1 prescaler (`_BV(CS10)`) on a 16 MHz arduino uno is too fast, giving 160000 counts per half-wave for 50Hz whereas Timer1 can only count to 65535. In theory the /64 prescaler (`_BV(CS11) | _BV(CS10)`) _would_ still work, just with reduced accuracy. (Since then everything would be measured in 4 &mu;s increments rather than 0.5 &mu;s increments.)

**Comment by woodlist** [comment]
You are so honest. Thanks a much for your support.

**Comment by AJMansfield** [comment]
By the way, out of curiosity what was it that prompted you to find this library? There's been a very sudden uptick in activity in just the last two days here, did someone reference this library in an article or video somewhere?

**Comment by woodlist** [comment]
I met that in Arduino library accidentaly, when was searching for absolutely another thing. Of course, I had a triac running task, but before getting your highly valued library, had intention to realise on traditional way, without arduino.

**Comment by AJMansfield** [comment]
Well, good to know. If you have any other issues feel free to ask.

**Comment by woodlist** [comment]
Greetings, Mr. Mansfield. The code works well upon phisical realisation. The only issue was angle firing definition in originally written embedded comments. If I understood correctly, immediate firing takes place on 0.0 and does not do opening at 1.0. But the review of performance by oscilloscope gave countervise opinion. Anway, I can state that the project is done. Thanks once again.

**Comment by AJMansfield** [comment]
Just to let you know in case you're still working with it: there's now a new version of the library that fixes the behavior so it all works properly now.

**Comment by woodlist** [comment]
Thanks for update. I hope, this will fix time to time the unpredictable phase shift to greather values.
